def calculate_bounding_box(data: dict) -> dict:
    """
    Aggregates bounding box information for entire paragraphs or sections.

    Parameters
    ----------
    data : dict
        The layout information dictionary generated by Tesseract.

    Returns
    -------
    dict
        Bounding box info (x, y, width, height) for each block.
    """
    blocks = {}
    n_boxes = len(data['text'])
    for i in range(n_boxes):
        if data['block_num'][i] not in blocks:
            blocks[data['block_num'][i]] = {
                'left': data['left'][i],
                'top': data['top'][i],
                'right': data['left'][i] + data['width'][i],
                'bottom': data['top'][i] + data['height'][i],
                'text': data['text'][i]
            }
        else:
            blocks[data['block_num'][i]]['right'] = max(
                blocks[data['block_num'][i]]['right'], data['left'][i] + data['width'][i])
            blocks[data['block_num'][i]]['bottom'] = max(
                blocks[data['block_num'][i]]['bottom'], data['top'][i] + data['height'][i])
            blocks[data['block_num'][i]]['text'] += " " + data['text'][i]
    
    return blocks
