from DocConvert.document_converter import DocumentConverter
from OCR.ocr_layout import OCRLayoutAnalyzer
from BoundBox.bounding_box import calculate_bounding_box
from LLM.analyzer import AdvancedLayoutAnalyzer

# Convert PDF to Images
converter = DocumentConverter("/home/josephmargaryan/DocIntel/data/sample.pdf")
converted_data = converter.convert()

# Extract text from the PDF using OCR
print(converted_data['text'])

# Perform OCR Layout Analysis
ocr_analyzer = OCRLayoutAnalyzer("/home/josephmargaryan/DocIntel/data/sample.pdf")
layout_data = ocr_analyzer.extract_text_with_layout()

# Calculate bounding boxes for the OCR'd text
bounding_boxes = calculate_bounding_box(layout_data[0])
print(bounding_boxes)

# Now analyze the layout for each converted image (not the PDF itself)
layout_analyzer = AdvancedLayoutAnalyzer()

# Iterate over the images generated by the PDF conversion
for image_path in converted_data['images']:
    print(f"Analyzing layout for image: {image_path}")
    layout_info = layout_analyzer.analyze_document(image_path)
    print(layout_info)


